[package]
name = "yuwir"
version = "0.1.0"
edition = "2021"
authors = ["Vz0n"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansi_term = "0.12.1"
